/** History aggregation, XP/rank scoring and the strength-standard gate.
 *  Re-exported from the shared engine so the declarations keep their original
 *  order. Import this module for scoring alone. */
export { bindHost } from './engine.js';
export {
  DOW,
  EFFORT_WORD,
  LIFT_DOWS,
  MEDALS,
  PACE_OFFSET,
  RACE_OFFSET,
  RUN_EXP,
  RUN_GOALS,
  RUN_SESSIONS,
  SOFTEN,
  STANDARDS,
  XP,
  allHistory,
  badgeList,
  bestOfAll,
  buildSchedule,
  consistency,
  defaultDows,
  dowOf,
  e1rm,
  fmtSec,
  gateCheck,
  gateLifts,
  isLowerDay,
  levelFor,
  levelType,
  localISO,
  lvlCost,
  maxOf,
  mi2,
  mondayKey,
  pace,
  paceFor,
  phaseOf,
  runExp,
  runSegments,
  runSession,
  scCtx,
  schCtx,
  schedNow,
  scoreState,
  segLine,
  segMiles,
  segPace,
  startDow,
  todayISO,
  topSet,
  totalMiles,
  trainDows,
  waveOf,
  weekCount,
  weekRows,
  weekStats
} from './engine.js';
